@host=http://localhost:3000/api/v1

### HEALTH
GET {{host}}/auth HTTP/1.1

### login
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "ggonzalesd",
	"password": "1234"
}

### Register
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
	"username": "archiso",
	"password": "1234",
	"display": "Archiso"
}

### Revoke
POST {{host}}/auth/revoke HTTP/1.1
Content-Type: application/json

{
	"id": "fc801aee-c84d-4858-a798-3660498a2c1b"
}

### Profile
GET {{host}}/auth/profile HTTP/1.1

### Logout
POST {{host}}/auth/logout HTTP/1.1

### Rooms
GET {{host}}/room HTTP/1.1

### Start ROOM
POST {{host}}/room/1 HTTP/1.1
