@host=http://localhost:3000/api/v1

### HEALTH
GET {{host}}/auth HTTP/1.1

### login
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "superadmin",
	"password": "12345678"
}

### Register
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2MGM0YzQ1LTQ4NTUtNDA3My05NDNiLTg1YTgwNzJiYWQ1MiIsInVzZXJuYW1lIjoiYXJjaGlzbyIsImhhc2giOiJkODc4NmZhNC05MTJkLTQ2NmQtYjc0MC1hNDFkYTFhNjJhYjkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTk1MTUwOTksImV4cCI6MTc1OTYwMTQ5OX0.Ih2xaknXazItEtbtYxNzGRQJxyXxVyGs-YrPNGwB6vo

{
	"username": "cristian",
	"password": "12345678",
	"display": "Cristian"
}

### Revoke
POST {{host}}/auth/revoke HTTP/1.1
Content-Type: application/json

{
	"id": "d84f5da6-9353-4b91-a3f6-1554ae3cb693"
}

### Profile
GET {{host}}/auth/profile HTTP/1.1

### Logout
POST {{host}}/auth/logout HTTP/1.1

### Rooms
GET {{host}}/room HTTP/1.1

### Start ROOM
POST {{host}}/room/main-room HTTP/1.1

### Stop ROOM
POST {{host}}/room/stop/main-room HTTP/1.1

### Experimental
GET {{host}}/experimental/manual-request-llm HTTP/1.1

### Update File
PUT {{host}}/skin/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWx

------WebKitFormBoundary7MA4YWx
Content-Disposition: form-data; name="file"; filename="skin.png"
Content-Type: image/png

< /home/archiso/Downloads/2025_05_09_astro-v4-23257593.png
------WebKitFormBoundary7MA4YWx--